### ISSUE TITLE
5 seconds hover and flip+crash - 3.0.1 R2

### ISSUE THREAD

**Issue by icsss** [MegaPirateNG/ardupilot-mpng#64] opened 2013-12-25 10:52 UTC
I was flying the first release of 3.0.1 R2 w/o problems (for several months) until I changed to a new frame; everything else is the same, PIDs, setup, etc.

I made a short 5 seconds hover 20cm above ground and suddenly the quad made a fast flip and crashed.

Before that I have tested the quad reaction "in hand" and everything looked right. Prop direction, gyro direction, etc..

Any ideas what happened? Maybe its vibration related issue?
Thanks.

**Comment by aussiepage** [comment] 2013-12-25 14:07
I had similar experience when speed controllers were not calibrated
correctly.  Would not have thought vibration would cause such a big issue.
 Did you check props were tight.

**Comment by SirAlex** [comment] 2013-12-25 14:08
R2 have known bug (this). Please, use R3

**Comment by icsss** [comment] 2013-12-25 17:38
Before switching to R3 I'm curious to find out why..

Was there a discussion about this? What was the cause of this?

PS: props ware tight, escs calibrated, everything was tested many times before on a previous frame with the same config.

**Comment by icsss** [comment] 2013-12-26 13:58
@SirAlex Can you please tell the couse of this bug in r2? I was flying r2 for months before this new frame.
I realy don't want to crash again, balancing 4 props is a pain in the !@#. Thanks!

**Comment by Waaas** [comment] 2014-01-02 00:39
I got the same problem with 3.0.1R2 version.
Every time when I lift above ground and suddenly the quad made a fast flip and crashed. I followed all the instructions and I am run out of ideas now.

**Comment by smurfy** [comment] 2014-01-02 00:47
> I got the same problem with 3.0.1R2 version.

as suggested befor by @SirAlex please use the R3 version instead

**Comment by Waaas** [comment] 2014-01-02 00:49
Dear Sir Alex could you please tell me what is the reliable firmware version to try. As I am a new to this hobby I want to at least lift from the ground and hoover for a start. Still I couldn't do that after lot of effort. I spend hours and hours for this project.. Read almost every article on the web. 
I got quad Copter with the following...
Hobby king Multiwii AIO Pro Ver 2.0 FC with 3.0.1R2 firmware loaded.
9XR Radio

**Comment by Waaas** [comment] 2014-01-02 00:50
Thanks for your prompt reply.
What is the link to the R3 version?
Thanks again.

**Comment by smurfy** [comment] 2014-01-02 00:52
All linked here: http://docs.megapirateng.com/documentation/compile

**Comment by Waaas** [comment] 2014-01-02 00:58
Thanks so much.
I will try this version and get back to you.
Appreciate your help.

**Comment by Waaas** [comment] 2014-01-02 22:56
Dear Sir Alex,
I followed the instructions as shows on your link.
I tried 3.0.1R3 version last night. I calibrated the radio, Accelerometer and the compass after download the new version.
Now the problem is,
When I armed the FC from 9xR radio with mission planner connected through USB, FC red light goes permanent then freezes the controller. It doesn't show that its changed to armed on mission planner. it completely frozen. then I have to disconnect and unplugged the USB cable to reset the FC. It has happened several times and exactly the same problem. I download the firmware three times and tried. exactly the same. Thinking not sufficient voltage to the controller from USB I connected the external UBEC as well. But the problem is when I armed it freezes. That mean Version 3.0.1R3 also not work for me for some reason. Any suggestion would be appreciate.
Thanks again

**Comment by Waaas** [comment] 2014-01-07 04:13
Please someone reply.

**Comment by Waaas** [comment] 2014-01-08 04:15
Dear Sir,
I followed the instructions as shows on your link.
I tried 3.0.1R3 version couple of days ago. I calibrated the radio, Accelerometer and the compass after download the new version.
Now the problem is,
When I armed the FC from 9xR radio with mission planner connected through USB, FC red light goes permanent then freezes the controller. It doesn't show that its changed to armed on mission planner. it completely frozen. Then I have to disconnect and unplugged the USB cable to reset the FC. It has happened several times and exactly the same problem. I download the firmware three times, and end up with exactly the same problem. Thinking not sufficient voltage to the controller from USB I connected the external UBEC as well. But the problem is when I armed it freezes. That means Version 3.0.1R3 also not work for me for some reason. Any suggestion would be appreciate.
Thanks again

Subject: Re: [ardupilot-mpng] 5 seconds hover and flip+crash - 3.0.1 R2 (#64)

All linked here: http://docs.megapirateng.com/documentation/compile

**Comment by edw00d4711** [comment] 2014-01-08 09:50
Do you have any logs/video?

**Comment by smurfy** [comment] 2014-01-08 16:43
I think only Crius V2 supports data logging. 

> Thinking not sufficient voltage to the controller from USB I connected the external UBEC as well. 

Do you mean instead of USB or connecting both? If you are connecting both please try to connect only the UBEC.

I also guess you set the board type correctly in your config right?

Something like freezing after arm only happend for me with multiwii, the problem there was a wrongly calibrated ACC and haveing the copter / board in a non plan position while arming. which caused multiwii to eat cpu like hell, but disarming still worked and the temporarily freeze stopped.

Don't know if this could happen to ardupilot aswell.

**Comment by Waaas** [comment] 2014-01-08 22:34
Dear sir,
No I don’t have any vedio.

My quad includes Multiwii/Megapirate AIO Pro controller as shown below.
I got Turnigy 9XR Radio to control this.
External GPS connected.

I am a beginner for this field and first time it works for 2.8R3 firmware and crashed couple of times before I learned to control properly.
Then I built this again and loaded with 3.0.R2 firmware because it has more features.

On the ground, it works perfectly.
I can communicate, Arm/Disarm, throttle up/down without and with propellers installed. I set the channel 6 to adjust the PID settings and tune everything.
Then I balance the Quad propellers and install them in correct way. I balance the sticks PWM to mid point and calibrated.
Then I put a string on the middle and balance the centre of gravity.
Then I set the all the modes to stabilise mode.
After checked everything I throttle up slowly until it about to lift off the ground.
When it just hoover 1cm above ground, I slowly increase the throttle.
It hoovers and flips nose up and crashed.
This was happen every time when I try with 3.0.R2.

Then I wrote this problem to forum in GitHub. Someone suggest me to try 3.0.R3.
When I download the firmware version 3.0.R3
I followed the instructions as shows on – link--> http://docs.megapirateng.com/documentation/compile.
Only thing I did was replace the shipped pde.jar from the source directory to the ardupilot-arduino software.
Then I compiled and uploaded the 3.0.1R3 version.
I calibrated the radio, Accelerometer and the compass after download the new version.

Now the problem is,
When I armed the FC from 9xR radio with mission planner connected through USB, FC red light goes permanent then freezes the controller.
It doesn't show that it has changed to arm on mission planner.
It has completely frozen. Then I have to disconnect and unplugged the USB cable to reset the FC.
It has happened several times and exactly the same problem.
I download the firmware three times, and end up with exactly the same problem.
Thinking not sufficient voltage to the controller from USB I connected the external UBEC while communicate with USB as well.
However, the problem is when I armed it freezes.
That means Version 3.0.1R3 also not work for me for some reason. Any suggestion would be appreciate.
Thank you kindly for your help

[Multiwii and Megapirate AIO Flight Controller w/FTDI  (ATmega 2560) V2.0]

To: MegaPirateNG/ardupilot-mpng

Subject: Re: [ardupilot-mpng] 5 seconds hover and flip+crash - 3.0.1 R2 (#64)

Do you have any logs/video?

**Comment by smurfy** [comment] 2014-01-08 22:50
Based on your detailed description you did not the board type to Crius 1, which is still almost identical as the Crius 2 default config but the crius 2 config also has enabled datalogging maybe this confuses the board.

You either could try the flashtool or continue the readme at http://docs.megapirateng.com/documentation/general_configuration

**Comment by Waaas** [comment] 2014-01-08 22:51
Dear Sir,

My quad includes Multiwii/Megapirate AIO Pro controller as shown below.
I got Turnigy 9XR Radio to control this.
External GPS connected.

I am a beginner for this field and first time it works for 2.8R3 firmware and crashed couple of times before I learned to control properly.
Then I built this again and loaded with 3.0.R2 firmware because it has more features.

On the ground, it works perfectly.
I can communicate, Arm/Disarm, throttle up/down without and with propellers installed. I set the channel 6 to adjust the PID settings and tune everything.
Then I balance the Quad propellers and install them in correct way. I balance the sticks PWM to mid point and calibrated.
Then I put a string on the middle and balance the centre of gravity.
Then I set the all the modes to stabilise mode.
After checked everything I throttle up slowly until it about to lift off the ground.
When it just hoover 1cm above ground, I slowly increase the throttle.
It hoovers and flips nose up and crashed.
This was happen every time when I try with 3.0.R2.

Then I wrote this problem to forum in GitHub. Then probably you or Someone suggest me to try 3.0.R3.
When I download the firmware version 3.0.R3
I followed the instructions as shows on – link--> http://docs.megapirateng.com/documentation/compile.
Only thing I did was replace the shipped pde.jar from the source directory to the ardupilot-arduino software.
I didn’t change anything else in the header files or source files.
Then I compiled and uploaded the 3.0.1R3 version.
I calibrated the radio, Accelerometer and the compass after download the new version.
Now the problem is,
When I armed the FC from 9xR radio with mission planner connected through USB, FC red light goes permanent then freezes the controller.
It doesn't show that it has changed to arm on mission planner.
It has completely frozen. Then I have to disconnect and unplugged the USB cable to reset the FC.
It has happened several times and exactly the same problem.
I download the firmware three times, and end up with exactly the same problem.
Thinking not sufficient voltage to the controller from USB I connected the external UBEC while communicate with USB as well.
However, the problem is when I armed it freezes.
That means Version 3.0.1R3 also not work for me for some reason. Any suggestion would be appreciate.
Thank you kindly for your help

[Multiwii and Megapirate AIO Flight Controller w/FTDI  (ATmega 2560) V2.0]

Sent: Thursday, 9 January 2014 3:43 AM

Subject: Re: [ardupilot-mpng] 5 seconds hover and flip+crash - 3.0.1 R2 (#64)

I think only Crius V2 supports data logging.

Thinking not sufficient voltage to the controller from USB I connected the external UBEC as well.

Do you mean instead of USB or connecting both? If you are connecting both please try to connect only the UBEC. It works ok with 3.0.1R2 with or without UBEC.

I also guess you set the board type correctly in your config right? I set the board type “X” on the mission planner.

Something like freezing after arm only happend for me with multiwii, the problem there was a wrongly calibrated ACC and haveing the copter / board in a non plan position while arming. which caused multiwii to eat cpu like hell, but disarming still worked and the temporarily freeze stopped.

Don't know if this could happen to ardupilot aswell.

**Comment by Waaas** [comment] 2014-01-08 23:11
I didn't delete the // on this //#define MPNG_BOARD_TYPE   CRIUS_V1
in APM_Config.h file.
since my board type is [Multiwii and Megapirate AIO Flight Controller w/FTDI  (ATmega 2560) V2.0]
do I have to set exactly as follows in APM_Config.h file? 
please confirm.
Thanks

#define MPNG_BOARD_TYPE   CRIUS_V1

**Comment by smurfy** [comment] 2014-01-08 23:46
> #define MPNG_BOARD_TYPE CRIUS_V1

yes, maybe this helps if not, i'm really out of ideas.

also the github thing is not really a forum. its an issue tracker :).

**Comment by Waaas** [comment] 2014-01-08 23:52
Thanks so much.
I try this and get back to you.

**Comment by Waaas** [comment] 2014-01-09 11:08
I manage to edit the APM-Config.h file as you advised and down loaded the
Firmware version 3.0.1R3.
Now I can arm/disarm without any problem.
Now it won't freeze the FC. Everything is sweet.
But when I lift from the ground it flips from nose up.
I tried with different PID parameters.
Still the same. Now I can confirm both version play exactly the same.
Appreciate any suggestions.

**Comment by edw00d4711** [comment] 2014-01-09 11:14
Your 100% sure your proppelers are spinning in the right direction?
http://s1097.photobucket.com/user/nebstress/media/MegaPirate_Frames.jpg.html

**Comment by SirAlex** [comment] 2014-01-09 11:20
1. erase EEPROM (all settings) go to Terminal and do `setup` and `erase` command.
2. Do all calibrations (Radio, compass, accelerometer)
3. Check prop and motor direction http://docs.megapirateng.com/documentation/connecting_components_copter
4. Calibrate ESC
5. Go to Terminal and run `test`, `motors` command (you must connect main LIPO). Motors will start in clockwise direction (motor by motor)

**Comment by Waaas** [comment] 2014-01-09 11:46
Yes it is 100% sure propellers are correct. Front right anticlockwise, rear left anticlockwise, front left clockwise and rear right clockwise. 
Thanks.

**Comment by Waaas** [comment] 2014-01-09 11:54
Thanks SirAlex I'll try that and get back to you.

**Comment by Waaas** [comment] 2014-01-09 22:09
Can anyone tell me what is the approximate value of Accel Z  on Mission Planner FLIGHT DATA screen.
my one always shows -1000 on ground. Which is minus value always, is that correct?

**Comment by Waaas** [comment] 2014-01-11 08:04
Thanks so much SirAlex,
I followed your advice. Erase the EEPROM .
Then calibrated everything as you said and tried.
It looks promising now. It is just hover about 1 cm above ground without flip. I have to try in a open area soon and will update the results.

Thanks so much to everyone who helped to solve this problem. I appreciate everyone for sharing your knowledge and experience.

**Comment by Waaas** [comment] 2014-01-11 08:19
Thanks so much smurty  for your help as well.

**Comment by Waaas** [comment] 2014-01-13 22:11
Dear SirAlex,
I tried my Quad Copter yesterday in an open area. Unfortunately it crashes again. this time it flipped nose down and crashed just after lift off from ground. I am run out of ideas now.
I am thinking of download 2.8R3 firmware again and try. Any suggestion would be appreciate. thank you kindly.

**Comment by gnalonso** [comment] 2014-01-16 18:46
Dear Waaas.
I kind of having the same problem with my quad this weekend as you can see in the youtube link: http://www.youtube.com/watch?v=l8-4Ujat7m4
I am on 3.0.1 R3 also but in my case looks like I had a bad soldering between the motors and speed control conectors causing the motor in the front/ right to stop during flight. I am deducting that because after the crash I noticed the "loose wire" in this motor and after checking the other conectors I confirmed that tree of them came out very easy im my hand.
I resoldered all connectors and should make some flights in the next few days to ensure my crash was not caused by the FW 3.0.1 R3.
BTW the motors were bought at Good Luck Buy toguether with the generic F-450 frame. I recomend you checking your motors principally if you have the same as I do. You can see them in the video.
I hope this can help you. I will post a comment after testing my resurected F-450.
Regards to all.

**Comment by Waaas** [comment] 2014-01-16 18:54
Thanks for your suggestion. I will check them carefully one by one.
Cheers

**Comment by gnalonso** [comment] 2014-01-16 23:17
Just flew 2 batteries this afternoon and so far no flipping issues. Everything working as expected. Regards to all.

**Comment by SirAlex** [comment] 2014-02-25 17:51
This issue was fixed in MPNG 3.0.1 R3

**Closed as completed by SirAlex** 2014-02-25 17:51 UTC
