### ISSUE TITLE
Megapirate-mpng not showing as HAL board

### ISSUE THREAD

**Issue by lucamoharram** [MegaPirateNG/ardupilot-mpng#108] opened 2014-02-27 10:01 UTC
I downloaded the ardupilot-arduino and replaced the pde.jar file with the one from ardupilot mpng but the HAL board selection still wont show me Megapirate 
Any help much appreciated thanks.

**Comment by smurfy** [comment] 2014-02-27 10:10
What system do you use? Windows/Mac/Linux?

Also did you restart your arduino ide and sure you start the ardupilot version of the ide.

Also if you only want to flash the firmware and use windows you can use the flashtool.

**Comment by lucamoharram** [comment] 2014-02-27 10:14
Windows 7 
How can i restart the ide?
Can i use the flash tool to setup with my NEO6M gps? and tune pi gains and values?

**Comment by lucamoharram** [comment] 2014-02-27 10:20
I you or anyone else knows of a full guide to setting up the CRIUS AIO PRO v2.0 with multiwii or megapirate and NEO6M that would be awsome...
Also is a 6ch radio enough for a quad with megapirate and gps or should i try multiwii?

**Comment by smurfy** [comment] 2014-02-27 10:26
> How can i restart the ide?

Close arduino software and start it again.

> Can i use the flash tool to setup with my NEO6M gps?
> Yes, GPS normally gets autodetected and you don't set it manually to a special on.
> What do you mean with pi gains or values? Do you mean PID Values? You can do that via Mission Planner / APM Planner 2.
> 
> Also is a 6ch radio enough for a quad with megapirate and gps 
> Yes, you need 4ch for movement and at least one more for the flight modes.

Just try the [FlashTool](http://docs.megapirateng.com/documentation/flashtool) 
Only thing you probably need to change is the RC Input if you don't use PPM.

Also i would suggest read the other topics in the documentation as-well.

**Comment by lucamoharram** [comment] 2014-02-27 11:03
thanks mate ill give those things a go

**Comment by lucamoharram** [comment] 2014-02-28 08:21
I tried to use the flash tool.. Used the CRIUS v1 AIOP option but i get error messages:

> C:/Users/Luca/Desktop/multiwii FC and KK2 stuff/megapirate/flashtool1_0rc2/external/avrdude.exe -CC:/Users/Luca/Desktop/multiwii FC and KK2 stuff/megapirate/flashtool1_0rc2/external/avrdude.conf -patmega2560 -cwiring -PCOM3 -b115200 -D -Uflash:w:C:/Users/Luca/Desktop/multiwii FC and KK2 stuff/megapirate/flashtool1_0rc2/firmwares/7ff7a49e359868d662f673fe8fb95cbc_555f662d7b2a2870fb003b58ced60b5fe9b8126b.hex:iavrdude.exe: stk500v2_ReceiveMessage(): timeout
> avrdude.exe: stk500v2_ReceiveMessage(): timeout
> avrdude.exe: stk500v2_ReceiveMessage(): timeout
> avrdude.exe: stk500v2_ReceiveMessage(): timeout
> avrdude.exe: stk500v2_ReceiveMessage(): timeout
> avrdude.exe: stk500v2_ReceiveMessage(): timeout
> avrdude.exe: stk500v2_getsync(): timeout communicating with programmer

avrdude.exe done.  Thank you.

**Comment by SirAlex** [comment] 2014-02-28 08:23
Your FC really connected to COM3?

**Comment by lucamoharram** [comment] 2014-02-28 08:33
yes

**Comment by lucamoharram** [comment] 2014-02-28 08:40
it says avrdude crashed..

**Comment by lucamoharram** [comment] 2014-02-28 08:46
I googled and others have had this problem with ATMEGA2650s One said they solved by updating to the newest arduino software. Is there a flash tool that uses a later code?

**Comment by smurfy** [comment] 2014-02-28 08:53
you could try replacing the avrdude.exe with a newer version. 
it ships with the same version as the ardupilot-arduino ide.

**Comment by lucamoharram** [comment] 2014-02-28 09:20
same issue...

**Comment by lucamoharram** [comment] 2014-03-01 05:45
this is the error im getting   http://www.instructables.com/id/A-solution-to-avrdude-stk500getsync-not-in-syn/
My problem is i cant fix the solution because its a flash tool...
Any ideas?

**Comment by lucamoharram** [comment] 2014-03-01 07:26
Flashed! To connect to reciever with PWM do i have to re-wire the servo connections from the reciever to have a common VCC and GROUND? There is only one pin for each so i would assume that is the signal pin... Or can i connect the throttle only with VCC and GROUND as they are most likely also joined in my reciever as well?
Im doing the second but if someone could confirm that would be great, Thanks.

**Comment by smurfy** [comment] 2014-03-08 21:46
If the problem is fixed please close this issue, Thanks

**Closed as completed** 2014-03-09 06:15 UTC
