### ISSUE TITLE
COM port not detected in Flashtool

### ISSUE THREAD

**Issue by leocopter** [MegaPirateNG/ardupilot-mpng#126] opened 2014-03-28 02:06 UTC
I'm trying to use Flashtool 1_0rc2. It is not detecting my COM port. I tried reassigning the COM port to a lower number. No go. I tried another HK AIOP board = no detection. Any idea of what's going on ?
(I can upload via Arduino and connect to Mission Planner, no problem).

**Comment by smurfy** [comment] 2014-03-29 08:53
please close this ticket, its a duplicate of the one at the flashtool repro

**Closed as completed** 2014-03-29 13:39 UTC
