### ISSUE TITLE
HK_RED_MULTIWII_PRO BOARD crash after ARM

### ISSUE THREAD

**Issue by SandroFly** [MegaPirateNG/ardupilot-mpng#24] opened 2013-10-23 20:53 UTC
HK Red Multiwii pro board - AC 3.1-rc4  -  Mission Planner 1.2.84 build 1.1.5044.12328

I have configured the code correctly, erase and reset from Terminal and calibrated compass, accelerometer and radio..  gps works properly ...

how to ARM the card via radio or via mission planner,  the card crash, and crash mission planner ...
after a few seconds the message:
"errore: no response from MAV"

the card works correctly with version 2.9...

**Comment by SirAlex** [comment] 2013-10-24 07:24
Why you tried 3.1-rc4 - it's alpha version. Just intermediate commit.

**Comment by SandroFly** [comment] 2013-10-24 10:23
Sorry, I was curious dell'autotune,
I hope I was helpful all the same.

thanks

**Comment by smurfy** [comment] 2013-10-24 11:05
@SandroFly try 3.0.1-r3  it's based on the latest stable version of ArduCopter and should be more stable.

**Comment by SandroFly** [comment] 2013-10-24 22:19
thanks, I just compiled version 3.0.1-r3, and everything seems to work well in laboratory tests with this card, try tomorrow with the propellers.

thanks to you.

**Comment by smurfy** [comment] 2013-10-26 11:12
@SandroFly Please close this ticket if the issue is resolved.

**Closed as completed** 2013-10-26 17:26 UTC
